# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/zibo_/Project_FPGA/Vivado_Project_Template/constraint/template_constraint.xdc

# Block Designs: bd/block_design/block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design || ORIG_REF_NAME==block_design} -quiet] -quiet

# IP: bd/block_design/ip/block_design_template_ip_1_0/block_design_template_ip_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_template_ip_1_0 || ORIG_REF_NAME==block_design_template_ip_1_0} -quiet] -quiet

# XDC: c:/Users/zibo_/Project_FPGA/Vivado_Project_Template/build/my_project.gen/sources_1/bd/block_design/block_design_ooc.xdc
